language: node_js

jdk:
    - openjdk6

python:
    - "2.7"

ruby:
    - "1.9"

node_js:
    - "0.10"

before_install:
    - "npm install -g typescript"
    - "sudo easy_install pip"
    - "sudo pip install flake8"

before_script:
    - "make"

script: "make test || echo"

notifications:
    email:
        - imasahiro9@gmail.com
        - matsumura.t.lab@gmail.com
    on_success: change
    on_failure: always
