language: python

python:
    - "2.7"

ruby:
    - "1.9"

node_js:
    - "0.10"

before_install:
    - "sudo apt-get install python ruby openjdk-6-jdk"

before_script:
    - "make"

script: "make test || echo"
