language: node_js

jdk:
    - openjdk6

python:
    - "2.7"

ruby:
    - "1.9"

node_js:
    - "0.10"
    - "0.9"

before_install:
    - "npm install -g typescript"

before_script:
    - "make"

script: "make test || echo"
