language: python

jdk:
    - openjdk6

python:
    - "2.7"

ruby:
    - "1.9"

node_js:
    - "0.10"

before_install:
    - "sudo npm install -g typescript"

before_script:
    - "make"

script: "make test || echo"
