#!/bin/sh

SourceDir=src/org/GreenTeaScript/
build=src/Python/

source=
source="${source} GreenTeaScript"
source="${source} GreenTeaTopObject"
source="${source} GreenTeaScriptTest"
source="${source} SourceGenerator"
source="${source} BashSourceGenerator"
source="${source} JavaScriptSourceGenerator"
source="${source} CSourceGenerator"
source="${source} JavaSourceGenerator"
source="${source} PerlSourceGenerator"
source="${source} PythonSourceGenerator"

ts=""

for s in ${source}; do
    perl src/Python/ConvertToPython.pl < ${SourceDir}${s}.java > ${build}${s}.py
done

