#!/bin/sh

SourceDir=src/
build=src/TypeScript/

source=
source="${source} GreenTeaScript"
source="${source} GreenTeaTopObject"
source="${source} GreenTeaScriptTest"
source="${source} SourceGenerator"
source="${source} BashSourceGenerator"
source="${source} JavaScriptSourceGenerator"
source="${source} CSourceGenerator"
source="${source} JavaSourceGenerator"
source="${source} PerlSourceGenerator"
source="${source} PythonSourceGenerator"
source="${source} ConstantFolder"

ts=""

for s in ${source}; do
    perl src/TypeScript/ToTypeScript.pl < ${SourceDir}${s}.java > ${build}${s}.ts
    ts="${ts} ${build}${s}.ts"
done

tsc ${build}/LangDeps.ts ${ts}
