#!/bin/sh

SourceDir=./src/org/GreenTeaScript/
build=src/TypeScript/

# These order of files is VERY IMPORTANT. 
# DO NOT CHANGE THE ORDER WITHOUT NECESSITY.
source=
source="${source} GreenTeaTopObject"
source="${source} GreenTeaArray"
source="${source} GreenTeaEnum"
source="${source} GreenTeaGrammar"
source="${source} GreenTeaObject"
source="${source} GreenTeaRuntime"
source="${source} GtNode"
source="${source} GtGenerator"
source="${source} SourceGenerator"
source="${source} GtGrammar"
source="${source} GtParserContext"
source="${source} GtNameSpace"
source="${source} GtFieldInfo"
source="${source} GtClassField"
source="${source} GtFunc"
source="${source} GtSyntaxPattern"
source="${source} GtSyntaxTree"
source="${source} GtToken"
source="${source} GtTokenContext"
source="${source} GtType"
source="${source} GtTypeEnv"
source="${source} GtStaticTable"
source="${source} GtSourceGenerator"
source="${source} JavaScriptSourceGenerator"
source="${source} BashSourceGenerator"
source="${source} CSourceGenerator"
source="${source} PerlSourceGenerator"
source="${source} PythonSourceGenerator"
source="${source} ScalaSourceGenerator"
source="${source} KonohaGrammar"
source="${source} GreenTeaScript"
source="${source} GtSourceBuilder"
#
ts=""

for s in ${source}; do
    perl src/TypeScript/ToTypeScript.pl ${SourceDir}${s}.java > ${build}${s}.ts
    ts="${ts} ${build}${s}.ts"
done

perl src/TypeScript/PackLibraries.pl lib > ${build}GreenTeaLibraries.ts
ts="${ts} ${build}GreenTeaLibraries.ts"
ts="${build}LibGreenTea.ts ${ts}"

cat ${ts} > ${build}GreenTea.ts

tsc ${build}GreenTea.ts
#tsc ${build}/LibGreenTea.ts ${ts}

